FROM node:latest as build-stage

WORKDIR /app

COPY ./web/ .

RUN yarn install
RUN yarn build

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY /nginx/conf/web.conf /etc/nginx/conf.d

EXPOSE 28080
